name: Android Build and Publish on Release

on:
  release:
    types: [published]
    paths:
      - '**/*.apk'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build    
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Rename
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk tts-server.apk
          mv app/build/outputs/apk/release/app-release-unsigned-signed.aab tts-server.aab
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tts-server.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
