name: Android Build and Publish on Release

on:
  release:
    types: [published]
    paths:
      - '**/*.apk'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build AAB
        run: |
          ./gradlew clean
          ./gradlew bundleRelease --no-daemon --warning-mode all

      - name: Sign AAB
        id: sign_app_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Build APK
        run: |
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon --warning-mode all

      - name: Sign APK
        id: sign_app_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}
          
      - name: Show artifacts
        run: |
          ls app/build/outputs/apk/release/
          ls app/build/outputs/bundle/release/

      - name: Rename
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk eja-surf.apk
          mv app/build/outputs/bundle/release/app-release.aab eja-surf.aab

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eja-surf.apk
            eja-surf.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
